platform :ios, '9.0'

target 'Safe Drive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Safe Drive
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMapsDirections'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'Alamofire'
  pod "Pulsator"
end
